---
apiVersion: v1
kind: Namespace
metadata:
  name: vinyl-lib-app
---
apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: vinyl-lib-app
  labels:
    app: vinyl-lib-app
  name: vinyl-lib-app
spec:
  replicas: 3
  selector:
    matchLabels:
      app: vinyl-lib-app
  template:
    metadata:
      labels:
        app: vinyl-lib-app
    spec:
      containers:
      - image: kporwit/vinyl_lib_app:v0.1.1
        name: vinyl-lib-app-container
        imagePullPolicy: Always
        ports:
          - containerPort: 8000
            name: hello-port
